#!/usr/bin/env fish
#
# USFMH One-Click Build, Flash & Run
#
# Usage:  ./run.sh [--port /dev/ttyACM0] [--skip-build] [--sample INDEX|all] [--plot] [--dump]
#
# SD card setup (do once):
#   1. Format SD card as FAT32
#   2. Copy filters.bin to SD card root  (generated by pythondemo/gens/generate_filter_bin.py)
#   3. Copy input.wav to SD card root    (16-bit mono 48 kHz WAV)
#

set SCRIPT_DIR (cd (dirname (status filename)); and pwd)
set HOST_DIR "$SCRIPT_DIR/pythondemo"

# Defaults
set PORT ""
set SKIP_BUILD false
set SAMPLE_INDEX ""
set SHOW_PLOT false
set SHOW_DUMP false

# Parse arguments
set i 1
while test $i -le (count $argv)
    switch $argv[$i]
        case --port
            set i (math $i + 1)
            set PORT $argv[$i]
        case --skip-build
            set SKIP_BUILD true
        case --sample
            set i (math $i + 1)
            if test $i -gt (count $argv)
                echo "ERROR: --sample requires an index value"
                exit 1
            end
            if not string match -rq '^(all|[0-9]+)$' -- $argv[$i]
                echo "ERROR: --sample must be 'all' or a non-negative integer"
                exit 1
            end
            set SAMPLE_INDEX $argv[$i]
        case --plot
            set SHOW_PLOT true
        case --dump
            set SHOW_DUMP true
        case -h --help
            echo "Usage: ./run.sh [--port PORT] [--skip-build] [--sample INDEX|all] [--plot] [--dump]"
            echo ""
            echo "  --port PORT            Serial port (auto-detected if not specified)"
            echo "  --skip-build           Skip firmware build step"
            echo "  --sample INDEX|all     Debug mode: skip hearing test and use one sample index or all active DSP bands"
            echo "  --plot                 Show filter arrangement and spectrum plots after processing"
            echo "  --dump                 Dump diagnostic data to dumps/ directory"
            echo ""
            echo "SD card must contain:"
            echo "  filters.bin   — FIR coefficients (generate with: python pythondemo/gens/generate_filter_bin.py)"
            echo "  input.wav     — 16-bit mono 48 kHz WAV file"
            exit 0
        case '*'
            echo "Unknown option: $argv[$i]"
            exit 1
    end
    set i (math $i + 1)
end

# ── Source ESP-IDF environment ──────────────────────────────────────────────
echo "━━━ Sourcing ESP-IDF environment ━━━"
source "$HOME/esp/esp-idf/export.fish"
echo "  IDF_PATH: $IDF_PATH"

# ── Auto-detect serial port ────────────────────────────────────────────────
if test -z "$PORT"
    for p in /dev/ttyACM0 /dev/ttyACM1 /dev/ttyUSB0 /dev/ttyUSB1
        if test -e "$p"
            set PORT "$p"
            break
        end
    end
    if test -z "$PORT"
        echo "ERROR: No serial port found. Connect your ESP32-S3 and retry."
        exit 1
    end
end
echo "  Using port: $PORT"

# ── Step 1: Build firmware ──────────────────────────────────────────────────
if test "$SKIP_BUILD" = false
    echo ""
    echo "━━━ Step 1: Building firmware ━━━"
    cd "$SCRIPT_DIR"
    idf.py build; or exit 1
    echo "  ✓ Build complete"
else
    echo ""
    echo "━━━ Step 1: Build skipped ━━━"
end

# ── Step 2: Flash firmware ──────────────────────────────────────────────────
echo ""
echo "━━━ Step 2: Flashing firmware ━━━"
cd "$SCRIPT_DIR"
idf.py -p "$PORT" flash; or exit 1
echo "  ✓ Firmware flashed"

# ── Step 3: Install Python dependencies ─────────────────────────────────────
echo ""
echo "━━━ Step 3: Checking Python dependencies ━━━"
/usr/bin/python3 -m pip install -q -r "$HOST_DIR/requirements.txt" 2>/dev/null
or /usr/bin/python3 -m pip install --user -q -r "$HOST_DIR/requirements.txt"
echo "  ✓ Dependencies ready"

# ── Step 4: Run the hearing test ─────────────────────────────────────────────
echo ""
if test -n "$SAMPLE_INDEX"
    echo "━━━ Step 4: Starting debug sample mode ━━━"
    echo "  Hearing test will be skipped."
    if test "$SAMPLE_INDEX" = all
        echo "  Mode: all DSP bands active"
    else
        echo "  Processing will use sample index: $SAMPLE_INDEX"
    end
else
    echo "━━━ Step 4: Starting hearing test ━━━"
    echo "  The ESP32 will reboot and the test will begin."
    echo "  You will hear tones — respond y/n for each."
end
echo ""

cd "$HOST_DIR"
set DEMO_ARGS --port "$PORT"
if test -n "$SAMPLE_INDEX"
    set DEMO_ARGS $DEMO_ARGS --sample "$SAMPLE_INDEX"
end
if test "$SHOW_PLOT" = true
    set DEMO_ARGS $DEMO_ARGS --plot
end
if test "$SHOW_DUMP" = true
    set DEMO_ARGS $DEMO_ARGS --dump
end
/usr/bin/python3 demo.py $DEMO_ARGS
